---
name: Bug Report
description: Report a bug or issue with the app.
title: "[Bug]"
labels: [bug]

body:
  - type: textarea
    id: app_version
    attributes:
      label: App Version
      description: Please specify the version of the app you are using.
  - type: textarea
    id: ios_version
    attributes:
      label: iOS Version
      description: Please specify your iOS version.
  - type: textarea
    id: device_type
    attributes:
      label: Device Type
      description: Please specify your device type (e.g., iPhone 12).
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Please provide the steps to reproduce the issue.
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
